Slack integration
TheCoreMan/valet-parking-slack-bot pull request #6
Opened 2021-09-28 17:13 UTC by DejaToris

2021-10-16 18:16 UTC, TheCoreMan requested changes

2021-10-16 18:16 UTC, TheCoreMan commented on src/valet_parking_slack_bot/server.py
> +)
1. Extract logging config to different file
2. the logging level should be determined from CLI and the default value should be "debug" (so that when we run on the cloud we'll only see info logs)

2021-10-16 18:16 UTC, TheCoreMan commented on src/valet_parking_slack_bot/server.py
> +              token=environ.get("SLACK_BOT_TOKEN"))
This looks weird. Let's set up `black` as a pre-commit hook to make the code nicely formatted.

(Should be a separate issue and PR)

2021-10-16 18:16 UTC, TheCoreMan commented on src/valet_parking_slack_bot/server.py
> +    #TODO translate UIDs to display names
Don't leave todos in the code. We have a tasklist on trello (there are a few)

2021-10-16 18:16 UTC, TheCoreMan commented on src/valet_parking_slack_bot/server.py
> +designator = ParkingSpotDesignator(repo)
Don't initialize these in the module-level code. Create a main function with two sub functions:

1. init, which does all this _gestures upwards_
2. run, which does what main is doing right now

You'll have to think about how to make the server resources (like the designator) available to the commands via OOP somehow, I don't have an immediate solution, try to look it up online

2021-10-16 18:16 UTC, TheCoreMan commented on src/valet_parking_slack_bot/server.py
> +user = 'test_user'
What is this, and why is it in main? Sounds like something that shouldn't be here.

```suggestion
```

2021-10-16 18:16 UTC, TheCoreMan commented on src/valet_parking_slack_bot/server.py
> +              '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'}
Add line number, function name, file name etc. to the message to make production debugging (i.e. trying to solve problems when it's running in the cloud) a lot easier: https://stackoverflow.com/questions/533048/how-to-log-source-file-name-and-line-number-in-python

2021-10-16 18:20 UTC, DejaToris commented on src/valet_parking_slack_bot/server.py
> +              token=environ.get("SLACK_BOT_TOKEN"))
Created an issue in Notion board

2021-10-16 18:21 UTC, DejaToris commented on src/valet_parking_slack_bot/server.py
> +    #TODO translate UIDs to display names
Uhmm ackshually it's on Notion

2021-10-16 18:25 UTC, DejaToris commented on src/valet_parking_slack_bot/server.py
> +user = 'test_user'
Just a const, it was useful before I implemented username extraction from context. I'll remove it

2021-10-17 09:45 UTC, DejaToris commented on src/valet_parking_slack_bot/server.py
> +)
I extracted the logging, but i'm not sure how to flag logging lev el from CLI. Seeing as there are more issues with the way the app is executed, I'll deal with that later.

2021-10-17 09:54 UTC, DejaToris commented on src/valet_parking_slack_bot/server.py
> +              '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'}
done

2021-10-18 06:30 UTC, merged